/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VivaVivaRouteImport } from './routes/viva/viva'
import { Route as VivaSelectTopicRouteImport } from './routes/viva/select-topic'
import { Route as VivaSelectRouteImport } from './routes/viva/select'
import { Route as VivaResultsRouteImport } from './routes/viva/results'
import { Route as VivaInstructionsRouteImport } from './routes/viva/instructions'
import { Route as VivaGateRouteImport } from './routes/viva/gate'
import { Route as VivaEvaluatingRouteImport } from './routes/viva/evaluating'
import { Route as ApiPublicSeedRouteImport } from './routes/api/public/seed'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaVivaRoute = VivaVivaRouteImport.update({
  id: '/viva/viva',
  path: '/viva/viva',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaSelectTopicRoute = VivaSelectTopicRouteImport.update({
  id: '/viva/select-topic',
  path: '/viva/select-topic',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaSelectRoute = VivaSelectRouteImport.update({
  id: '/viva/select',
  path: '/viva/select',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaResultsRoute = VivaResultsRouteImport.update({
  id: '/viva/results',
  path: '/viva/results',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaInstructionsRoute = VivaInstructionsRouteImport.update({
  id: '/viva/instructions',
  path: '/viva/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaGateRoute = VivaGateRouteImport.update({
  id: '/viva/gate',
  path: '/viva/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaEvaluatingRoute = VivaEvaluatingRouteImport.update({
  id: '/viva/evaluating',
  path: '/viva/evaluating',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedRoute = ApiPublicSeedRouteImport.update({
  id: '/api/public/seed',
  path: '/api/public/seed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/viva/evaluating': typeof VivaEvaluatingRoute
  '/viva/gate': typeof VivaGateRoute
  '/viva/instructions': typeof VivaInstructionsRoute
  '/viva/results': typeof VivaResultsRoute
  '/viva/select': typeof VivaSelectRoute
  '/viva/select-topic': typeof VivaSelectTopicRoute
  '/viva/viva': typeof VivaVivaRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/viva/evaluating': typeof VivaEvaluatingRoute
  '/viva/gate': typeof VivaGateRoute
  '/viva/instructions': typeof VivaInstructionsRoute
  '/viva/results': typeof VivaResultsRoute
  '/viva/select': typeof VivaSelectRoute
  '/viva/select-topic': typeof VivaSelectTopicRoute
  '/viva/viva': typeof VivaVivaRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/viva/evaluating': typeof VivaEvaluatingRoute
  '/viva/gate': typeof VivaGateRoute
  '/viva/instructions': typeof VivaInstructionsRoute
  '/viva/results': typeof VivaResultsRoute
  '/viva/select': typeof VivaSelectRoute
  '/viva/select-topic': typeof VivaSelectTopicRoute
  '/viva/viva': typeof VivaVivaRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/viva/evaluating'
    | '/viva/gate'
    | '/viva/instructions'
    | '/viva/results'
    | '/viva/select'
    | '/viva/select-topic'
    | '/viva/viva'
    | '/api/public/seed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/viva/evaluating'
    | '/viva/gate'
    | '/viva/instructions'
    | '/viva/results'
    | '/viva/select'
    | '/viva/select-topic'
    | '/viva/viva'
    | '/api/public/seed'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/viva/evaluating'
    | '/viva/gate'
    | '/viva/instructions'
    | '/viva/results'
    | '/viva/select'
    | '/viva/select-topic'
    | '/viva/viva'
    | '/api/public/seed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  VivaEvaluatingRoute: typeof VivaEvaluatingRoute
  VivaGateRoute: typeof VivaGateRoute
  VivaInstructionsRoute: typeof VivaInstructionsRoute
  VivaResultsRoute: typeof VivaResultsRoute
  VivaSelectRoute: typeof VivaSelectRoute
  VivaSelectTopicRoute: typeof VivaSelectTopicRoute
  VivaVivaRoute: typeof VivaVivaRoute
  ApiPublicSeedRoute: typeof ApiPublicSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/viva': {
      id: '/viva/viva'
      path: '/viva/viva'
      fullPath: '/viva/viva'
      preLoaderRoute: typeof VivaVivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/select-topic': {
      id: '/viva/select-topic'
      path: '/viva/select-topic'
      fullPath: '/viva/select-topic'
      preLoaderRoute: typeof VivaSelectTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/select': {
      id: '/viva/select'
      path: '/viva/select'
      fullPath: '/viva/select'
      preLoaderRoute: typeof VivaSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/results': {
      id: '/viva/results'
      path: '/viva/results'
      fullPath: '/viva/results'
      preLoaderRoute: typeof VivaResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/instructions': {
      id: '/viva/instructions'
      path: '/viva/instructions'
      fullPath: '/viva/instructions'
      preLoaderRoute: typeof VivaInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/gate': {
      id: '/viva/gate'
      path: '/viva/gate'
      fullPath: '/viva/gate'
      preLoaderRoute: typeof VivaGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viva/evaluating': {
      id: '/viva/evaluating'
      path: '/viva/evaluating'
      fullPath: '/viva/evaluating'
      preLoaderRoute: typeof VivaEvaluatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed': {
      id: '/api/public/seed'
      path: '/api/public/seed'
      fullPath: '/api/public/seed'
      preLoaderRoute: typeof ApiPublicSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  VivaEvaluatingRoute: VivaEvaluatingRoute,
  VivaGateRoute: VivaGateRoute,
  VivaInstructionsRoute: VivaInstructionsRoute,
  VivaResultsRoute: VivaResultsRoute,
  VivaSelectRoute: VivaSelectRoute,
  VivaSelectTopicRoute: VivaSelectTopicRoute,
  VivaVivaRoute: VivaVivaRoute,
  ApiPublicSeedRoute: ApiPublicSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
