from fastapi import APIRouter, File, HTTPException, UploadFile

from services.deepgram_transcriber import transcribe_audio

router = APIRouter(
    prefix="/transcribe",
    tags=["Transcription"],
)


@router.post("/")
async def transcribe(file: UploadFile = File(...)):
    """
    Accepts an uploaded audio file (.webm from MediaRecorder)
    Returns the transcript generated by Deepgram.
    """

    try:
        audio_bytes = await file.read()

        if not audio_bytes:
            raise HTTPException(
                status_code=400,
                detail="Empty audio file received.",
            )

        transcript = transcribe_audio(audio_bytes)

        return {
            "success": True,
            "transcript": transcript,
        }

    except HTTPException:
        raise

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Transcription failed: {str(e)}",
        )